name: Lint

on:
  push:
  pull_request:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v1.9.3
        with:
          # Exclude twitter.com (https://github.com/lycheeverse/lychee/issues/989)
          args: README.md --verbose --no-progress --exclude twitter.com
          fail: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: |
            README.md
            contributing.md

  awesome-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: npx awesome-lint
